name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-06-20"
account_id = "22e93a040a9ba3933abe6112c497b009"
main = "./build/index.js"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "50a2495a80a2ff963bf7c6fb1d05e848"
# MAX_WEBCAM_BITRATE="1200000"
# MAX_WEBCAM_FRAMERATE="24"
# MAX_WEBCAM_QUALITY_LEVEL="1080"

[durable_objects]
 bindings = [
  { name = "rooms", class_name = "ChatRoom" }
]

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`
